CREATE TABLE IF NOT EXISTS prompts
(
    title TINYTEXT NOT NULL,
    id INTEGER PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS segments
(
    prompt_id INTEGER NOT NULL,
    color TINYTEXT NOT NULL,
    text TINYTEXT NOT NULL,
    FOREIGN KEY(prompt_id) REFERENCES prompts(id)
);